---
image_definition: &image_definition
  platform: linux

  image_resource:
    type: docker-image
    source:
      repository: openjdk
      tag: 8-jdk

resources:
- name: source-code
  type: git
  source:
    uri: https://github.com/dlresende/spring-petclinic.git
    branch: concourse-live-demo

jobs:
- name: build
  plan:
  - get: source-code
    trigger: true
  - task: build
    config:
      <<: *image_definition

      inputs:
      - name: source-code
        path: .

      run:
        path: ./mvnw
        args:
          - compile

- name: test
  plan:
  - get: source-code
    trigger: true
    passed: [build]
  - task: test
    config:
      <<: *image_definition
      inputs:
      - name: source-code
        path: .

      run:
        path: ./mvnw
        args:
          - test

