#!/usr/bin/env bash

set -e

[ -z "${DEBUG:-}" ] || set -x

: "${CF_API:?}"
: "${CF_USERNAME:?}"
: "${CF_PASSWORD:?}"
: "${CF_ORG:?}"
: "${CF_SPACE:?}"

export CF_USERNAME CF_PASSWORD

JAR=${1:?}

main() {
	check_dependencies \
		cf \

	deploy
}

check_dependencies() {
  for bin in "$@"
  do
    if ! command -v "$bin" > /dev/null
    then
      echo "$bin required, but not found in PATH."
      exit 1
    fi
  done
}

deploy() {
	cf api --skip-ssl-validation "$CF_API"
  cf auth
	cf target -o "$CF_ORG" -s "$CF_SPACE"
  cf push "petclinic-$CF_SPACE" -p $JAR
}

main
