#!/usr/bin/env bash

set -e

[ -z "${DEBUG:-}" ] || set -x

: "${CF_API:?}"
: "${CF_USERNAME:?}"
: "${CF_PASSWORD:?}"
: "${CF_ORG:?}"
: "${CF_SPACE:?}"

export CF_USERNAME CF_PASSWORD

main() {
  local jar="${1:?}"

	check_dependencies \
		cf \

	deploy "$jar"
}

check_dependencies() {
  for bin in "$@"
  do
    if ! command -v "$bin" > /dev/null
    then
      echo "$bin required, but not found in PATH."
      exit 1
    fi
  done
}

deploy() {
  local jar="${1:?}"

	cf api "$CF_API"
  cf auth
	cf target -o "$CF_ORG" -s "$CF_SPACE"
	cf push "petclinic-$CF_SPACE" -p "$jar"
}

main "${1:?}"
